SERVER_NAME = "DESKTOP-JJT739B\\SQLEXPRESS"
DATABASE_NAME = "jobs"
DRIVER_NAME = "ODBC Driver 17 for SQL Server"

DB_CONNECTION_URI = f"mssql+pyodbc://@{SERVER_NAME}/{DATABASE_NAME}?driver={DRIVER_NAME}"